AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer with Target Group and Listener

Parameters:
  Environment:
    Type: String
    Default: test

Resources:
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${Environment} ALB Security Group"
      VpcId:
        Fn::ImportValue: !Sub "${Environment}-vpc-id"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-alb-sg"

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${Environment}-alb"
      Scheme: internet-facing
      Subnets:
        - Fn::ImportValue: !Sub "${Environment}-subnet-1-id"
        - Fn::ImportValue: !Sub "${Environment}-subnet-2-id"
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-alb"

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${Environment}-tg"
      Port: 80
      Protocol: HTTP
      VpcId:
        Fn::ImportValue: !Sub "${Environment}-vpc-id"
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-tg"

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  LoadBalancerDNSName:
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Sub "${Environment}-alb-dns"

  TargetGroupArn:
    Value: !Ref TargetGroup
    Export:
      Name: !Sub "${Environment}-tg-arn"

  LoadBalancerArn:
    Value: !Ref LoadBalancer
    Export:
      Name: !Sub "${Environment}-alb-arn"

  ALBSecurityGroupId:
    Value: !Ref LoadBalancerSecurityGroup
    Export:
      Name: !Sub "${Environment}-alb-sg-id"
