name: 1. Deploy ECS IAM Roles

on:
  workflow_dispatch:
  push:
    paths:
      - infra/role/**

jobs:
  deploy-role:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: dev
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set script permissions
        run: chmod +x ./infra/*.sh ./infra/role/*.sh

      - name: Deploy Role
        run: ./infra/deploy.sh ecs-role ./infra/role/role.yaml

      - name: Test Role
        run: |
          if ! ./infra/role/test-role.sh; then
          echo "Test failed, rolling back..."
          ./infra/delete.sh role
          exit 1
          fi

      - name: Success message
        run: echo "IAM Role stack deployed and validated successfully."
